version: '2'
services:
    db:
        image: mysql:5.7
        ports:
            - "32000:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./db:/docker-entrypoint-initdb.d/:ro
    app:
        build: ./servidor
        ports:
            - "5000:5000"
    interfaz:
        build: ./interfaz
        links:
            - app
            - db
        ports:
            - "3000:3000"
        volumes:
            - ./interfaz:/usr/src/app
